//! Core type definitions for SuperBrain (Tauri port - NAPI removed)

use serde::{Deserialize, Serialize};

/// Memory types supported by SuperBrain
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub enum MemoryType {
    Episodic,
    #[default]
    Semantic,
    Procedural,
    Working,
    Meta,
    Causal,
    Goal,
    Emotional,
}

/// Thought types for cognitive processing
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThoughtType {
    Observation,
    Inference,
    Hypothesis,
    Plan,
    Reflection,
    Synthesis,
    Evaluation,
    Creative,
}

/// Learning algorithm types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LearningType {
    QLearning,
    SARSA,
    ActorCritic,
    PolicyGradient,
    CuriosityDriven,
    MetaLearning,
}

/// Distance metrics for vector similarity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum DistanceMetric {
    #[default]
    Cosine,
    Euclidean,
    DotProduct,
    Manhattan,
}

/// Memory entry stored in the cognitive system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub id: String,
    pub content: String,
    pub memory_type: String,
    pub importance: f64,
    pub decay: f64,
    pub access_count: u32,
    pub timestamp: i64,
    pub connections: Vec<String>,
}

/// Thought generated by cognitive processing
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Thought {
    pub id: String,
    pub content: String,
    pub thought_type: String,
    pub confidence: f64,
    pub novelty: f64,
    pub utility: f64,
    pub timestamp: i64,
}

/// Learning experience for training
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Experience {
    pub state: Vec<f64>,
    pub action: u32,
    pub reward: f64,
    pub next_state: Vec<f64>,
    pub done: bool,
}

/// Learning outcome after processing
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LearningOutcome {
    pub success: bool,
    pub reward: f64,
    pub td_error: f64,
    pub insights: Vec<String>,
}

/// Configuration for the cognitive engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CognitiveConfig {
    pub dimensions: u32,
    pub max_memories: u32,
    pub decay_rate: f64,
    pub learning_rate: f64,
    pub exploration_rate: f64,
    pub discount_factor: f64,
    pub batch_size: u32,
}

impl Default for CognitiveConfig {
    fn default() -> Self {
        Self {
            dimensions: 384,
            max_memories: 100_000,
            decay_rate: 0.01,
            learning_rate: 0.01,
            exploration_rate: 0.1,
            discount_factor: 0.99,
            batch_size: 32,
        }
    }
}

/// Statistics about the cognitive system
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CognitiveStats {
    pub total_memories: u32,
    pub total_thoughts: u32,
    pub total_experiences: u32,
    pub avg_importance: f64,
    pub avg_reward: f64,
    pub learning_trend: f64,
}

pub fn parse_memory_type(s: &str) -> MemoryType {
    match s.to_lowercase().as_str() {
        "episodic" => MemoryType::Episodic,
        "semantic" => MemoryType::Semantic,
        "procedural" => MemoryType::Procedural,
        "working" => MemoryType::Working,
        "meta" => MemoryType::Meta,
        "causal" => MemoryType::Causal,
        "goal" => MemoryType::Goal,
        "emotional" => MemoryType::Emotional,
        _ => MemoryType::Semantic,
    }
}
